version: '3'
services:
  web:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - '80:80'
  share:
    image: wernight/ngrok
    ports:
      - '4040:4040'
    links:
      - 'web'